application:
  port: 8000
  # this is not a real secret, the actual key is provided via an environment variable in production
  # (and may not actually be used anywhere?)
  hmac_secret: "long-and-very-secret-random-key-needed-to-verify-message-integrity"
  # also a fake secret, provided at runtime
  totp_encryption_key: "f2e4f32183efde11831c64557303bf22"
  # ok in hindsight, it's still probably a bad idea to expose secrets like this,
  # even if they aren't the ones I'll actually use in production, so this will
  # just be a path to the .pem now
  jwt_private_key: "./jwt_ec_private.pem"
database:
  host: "localhost"
  port: 5432
  # similarly, these are not real keys, the prod values are in the prod environment
  username: "postgres"
  password: "password"
  database_name: "portfolio"
ttl:
  ttl_hours: 1
  idle_timeout_minutes: 15
redis_uri: "redis://127.0.0.1:6379"