application:
  host: 127.0.0.1
  base_url: "http://127.0.0.1"
database:
  require_ssl: false
cors:
  allowed_origins:
    - "http://localhost:4200"
  max_age: 3600
ttl:
  idle_timeout_minutes: 1
rate_limit:
  login:
    max_requests: 3
    window_secs: 1
  message:
    max_messages: 3
    window_minutes: 1