application:
  host: 0.0.0.0
database:
  require_ssl: true
cors:
  allowed_origins:
    - "https://devogel.dev"
rate_limit:
  login:
    max_requests: 3
    window_secs: 10
  message:
    max_messages: 3
    window_minutes: 60