application:
  host: 0.0.0.0
database:
  require_ssl: true
cors:
  allowed_origins:
    - "https://devogel.dev"
  max_age: 3600
rate_limit:
  login:
    max_requests: 10
    window_secs: 1
  totp:
    max_requests: 10
    window_secs: 1
  message:
    max_messages: 3
    window_minutes: 60
redis_uri: "UNSET_CONFIGURE_VIA_APP_REDIS_URI"